# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Conga < Formula
  desc "Conga Line — manage your OpenClaw deployment"
  homepage "https://github.com/cruxdigital-llc/conga-line"
  version "0.0.21"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cruxdigital-llc/CongaLine/releases/download/v0.0.21/conga_darwin_amd64.tar.gz"
      sha256 "dca7951db614a15d64da126a9938f951e7aa4955ae182ab420b38376fb0a2f55"

      define_method(:install) do
        bin.install "conga"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cruxdigital-llc/CongaLine/releases/download/v0.0.21/conga_darwin_arm64.tar.gz"
      sha256 "cb066868a08497c19f888c19bb7d985dcca8bd66fb23ebe6e4d1b17f9346b009"

      define_method(:install) do
        bin.install "conga"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cruxdigital-llc/CongaLine/releases/download/v0.0.21/conga_linux_amd64.tar.gz"
      sha256 "8bc04be2897b19d5356aba0e0ec9f3ead9956103f238eac18c1cb0c27da5d6ee"
      define_method(:install) do
        bin.install "conga"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cruxdigital-llc/CongaLine/releases/download/v0.0.21/conga_linux_arm64.tar.gz"
      sha256 "c5ae27dede03b470f7ae2b39a2126306618daae7e8eb57ec4296c31bfaf2dd95"
      define_method(:install) do
        bin.install "conga"
      end
    end
  end

  test do
    system "#{bin}/conga", "version"
  end
end
