# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Conga < Formula
  desc "Conga Line — manage your OpenClaw deployment"
  homepage "https://github.com/cruxdigital-llc/conga-line"
  version "0.0.22"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cruxdigital-llc/CongaLine/releases/download/v0.0.22/conga_darwin_amd64.tar.gz"
      sha256 "2997bfc55cf63ca0343052ffcbac326127a74e801017c214ce2c78f8ae5a6f8e"

      define_method(:install) do
        bin.install "conga"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cruxdigital-llc/CongaLine/releases/download/v0.0.22/conga_darwin_arm64.tar.gz"
      sha256 "e0847435b202d8127ee7a094bcdbb901cbc20967897f6d6cc3b2a15fd2122fd6"

      define_method(:install) do
        bin.install "conga"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cruxdigital-llc/CongaLine/releases/download/v0.0.22/conga_linux_amd64.tar.gz"
      sha256 "5332d85ad32568d5e46295d19b2cd67e98ce35386628eee8f6bad73dcce4d59b"
      define_method(:install) do
        bin.install "conga"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cruxdigital-llc/CongaLine/releases/download/v0.0.22/conga_linux_arm64.tar.gz"
      sha256 "cb1bb3405bbb0daf326f054264c15f031145eb8ae5a3216cf7a370002cb5eb85"
      define_method(:install) do
        bin.install "conga"
      end
    end
  end

  test do
    system "#{bin}/conga", "version"
  end
end
